### ISSUE TITLE
ForegroundServiceDidNotStartInTimeException sometimes on Android 13

### ISSUE THREAD

**Issue by bk138** [bk138/multivnc#230]
Process: com.coboltforge.dontmind.multivnc, PID: 16143
                                                                                                    android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7bacb4c u0 com.coboltforge.dontmind.multivnc/.ui.VNCConnService}
                                                                                                    	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
                                                                                                    	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
                                                                                                    	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1988)
                                                                                                    	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
                                                                                                    	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
                                                                                                    	at com.coboltforge.dontmind.multivnc.ui.VNCConnService$Companion$deregister$1.invokeSuspend(VNCConnService.kt:58)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by bk138** [comment]
Maybe-fixed by 060a1eb96e7a16361a92d484515d6419801a4794
