### ISSUE TITLE
Android touchpad mode disconnects after some time

### ISSUE THREAD

**Issue by bk138** [bk138/multivnc#94]
If you'd like to put out an incentive for fixing this bug, you can do so at https://issuehunt.io/r/bk138/multivnc?tab=idle

**Comment by bk138** [comment]
Vino says:

```
30/01/2021 12:48:27 rfbProcessClientNormalMessage: read: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
30/01/2021 12:48:27 Client ultramofo.lan gone
30/01/2021 12:48:27 Statistics:
30/01/2021 12:48:27   key events received 0, pointer events 136
30/01/2021 12:48:27   framebuffer updates 12, rectangles 1845, bytes 2100586
30/01/2021 12:48:27     LastRect and NewFBSize markers 12, bytes 144
30/01/2021 12:48:27     tight rectangles 1833, bytes 2100442
30/01/2021 12:48:27   raw bytes equivalent 99400988, compression ratio 47,323843
```

**Comment by bk138** [comment]
MultiVNC says:
```
2021-01-30 13:12:05.848 19966-20090/com.coboltforge.dontmind.multivnc I/VNCConn-native: Error reading from TLS: -.
2021-01-30 13:12:05.849 19966-20090/com.coboltforge.dontmind.multivnc E/VNCConn-native: read (4: Interrupted system call)
2021-01-30 13:12:05.849 19966-20090/com.coboltforge.dontmind.multivnc I/VNCConn-native: VNC server closed connection
2021-01-30 13:12:05.850 19966-20090/com.coboltforge.dontmind.multivnc E/VNCConn-native: com.coboltforge.dontmind.multivnc.VNCConn@2b78622: rfbProcessServerMessage() failed
2021-01-30 13:12:05.851 19966-20090/com.coboltforge.dontmind.multivnc E/VNCConn: java.lang.Exception
2021-01-30 13:12:05.854 19966-20090/com.coboltforge.dontmind.multivnc W/System.err: java.lang.Exception
2021-01-30 13:12:05.855 19966-20090/com.coboltforge.dontmind.multivnc W/System.err:     at com.coboltforge.dontmind.multivnc.VNCConn$ServerToClientThread.run(VNCConn.java:220)
2021-01-30 13:12:05.868 19966-20090/com.coboltforge.dontmind.multivnc I/VNCConn-native: com.coboltforge.dontmind.multivnc.VNCConn@2b78622: rfbShutdown() closing connection
2021-01-30 13:12:05.877 19966-20090/com.coboltforge.dontmind.multivnc D/VNCConn: ServerToClientThread done!
```

**Comment by bk138** [comment]
Takes 6 minutes.

**Comment by bk138** [comment]
Acquiring a wifi lock does _not_ help :no_entry: .

**Comment by bk138** [comment]
Happens w/ x11vnc as well.

**Comment by bk138** [comment]
For an unencrypted connection with systems logs as well:
```
01-30 20:40:50.542  3322  3637 E IptablesRestoreController: , res : 0
01-30 20:40:50.542  3664  3700 I libsuspend: !@suspend_thread_func: read wakeup_count +
01-30 20:40:50.544 24380 25535 D VNCConn : got server cuttext: d
01-30 20:40:50.545 24380 25535 D VNCConn : got server cuttext: Android: added support for handling Stylus button as right mouse button
01-30 20:40:50.550  3322 31903 I Netd    : Destroyed 2 sockets for UidRanges{ 10000-2147483647 } skip={1000 1001 1002 1027 1201 1250 2000 5002 5003 5010 10003 10004 10005 10015 10016 10019 1
0024 10027 10029 10033 10035 10043 10045 10046 10051 10057 10065 10070 10072 10075 10078 10082 10084 10085 10102 10116 10118 10157 10165 10185 10197 10259 10261 10263 10806 10868 99578} in 5
.8 ms
01-30 20:40:50.551 24380 25535 E VNCConn-native: read (103: Software caused connection abort)
01-30 20:40:50.551 24380 25535 E VNCConn-native: com.coboltforge.dontmind.multivnc.VNCConn@f480b2: rfbProcessServerMessage() failed
01-30 20:40:50.551 24380 25535 E VNCConn : java.lang.Exception
01-30 20:40:50.552  3664  3691 E BatteryStatsService: no controller energy info supplied
01-30 20:40:50.553 24380 25535 W System.err: java.lang.Exception
01-30 20:40:50.554 24380 25535 W System.err:    at com.coboltforge.dontmind.multivnc.VNCConn$ServerToClientThread.run(VNCConn.java:215)
01-30 20:40:50.554 24380 25535 I VNCConn-native: com.coboltforge.dontmind.multivnc.VNCConn@f480b2: rfbShutdown() closing connection
01-30 20:40:50.555 24380 25535 D VNCConn : ServerToClientThread done!
```

**Comment by bk138** [comment]
Basically: https://developer.android.com/training/monitoring-device-state/doze-standby.html#whitelisting-cases

**Comment by bk138** [comment]
ForegroundService solves this.
